pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "./outputs/close-up-baby-feet"
train_data:
  video_path: data/WebVid/stock-footage--close-up-baby-feet-learning-to-stand.mp4
  prompt: close up of a baby feet
  n_sample_frames: 8
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 1
validation_data:
  prompts:
  - close up of a tiger feet
  - close up of a bear feet
  video_length: 8
  width: 512
  height: 512
  num_inference_steps: 5
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 5
learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 5
checkpointing_steps: 10        
validation_steps: 5
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
