pretrained_model_path: /group/30042/zhangjiewu/downloads/mo-di-diffusion
output_dir: ./outputs/bear_guitar
train_data:
  video_path: data/bear-guitar/bear-guitar.mp4
  prompt: a bear is playing guitar
  n_sample_frames: 8
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 1
validation_data:
  prompts:
  - a handsome prince is playing guitar in the summer forest, modern disney style
  - a magical princess is playing guitar on the beach, modern disney style
  - a rabbit is playing guitar, modern disney style
  - a baby is playing guitar, modern disney style
  video_length: 8
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 7.5
validation_steps: 100
trainable_modules:
- attn1.to_q
- attn2.to_q
- attn_temp
train_batch_size: 1
max_train_steps: 500
learning_rate: 3.0e-05
scale_lr: false
lr_scheduler: constant
lr_warmup_steps: 0
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1.0e-08
max_grad_norm: 1.0
gradient_accumulation_steps: 1
gradient_checkpointing: true
checkpointing_steps: 1000
resume_from_checkpoint: null
mixed_precision: fp16
use_8bit_adam: false
enable_xformers_memory_efficient_attention: true
seed: 33
