pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "./outputs/woman-with-digital-tablet"

train_data:
  video_path: "data/WebVid/woman-with-digital-tablet.mp4"
  prompt: "a woman is using digital tablet"
  n_sample_frames: 8 
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 2
validation_data:
  prompts:
    - "a man is using digital tablet"
    - "micky mouse is using digital tablet"
    - "a spiderman is using digital tablet"
    - "a cat is using digital tablet"
  video_length: 8
  width: 512
  height: 512
  num_inference_steps: 10
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 10
learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 10
checkpointing_steps: 10
validation_steps: 10
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"
seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
