pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "./outputs/woman-eating-pizza"
train_data:
  video_path: data/WebVid/stock-footage-woman-is-eating-pizza-at-home.mp4
  prompt: a woman is eating pizza at home
  n_sample_frames: 16
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 1
validation_data:
  prompts:
  - a man is eating pizza at home
  - a bear is eating pizza
  video_length: 16
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50
learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 20
checkpointing_steps: 100        
validation_steps: 20
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"
seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
